language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "Pre-testing install - nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "Testing container app"
  - npm i
  - cd backend
  - npm run test

script:
  # These build will happen in the Travis worker node
  - docker --version # print the version for logging
  - docker build -t udacity-web-app ./backend
  - docker tag udacity-web-app fr3d3rico/udacity-web-app:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fr3d3rico/udacity-web-app:latest