apiVersion: v1
kind: Service
metadata:
 labels:
   app: backend-CIRCLE_WORKFLOW_ID
 name: backend-CIRCLE_WORKFLOW_ID
spec:
 ports:
 - name: '3000'
   port: 3000
   targetPort: 3000
 selector:
   app: backend-CIRCLE_WORKFLOW_ID
 type: LoadBalancer #Allow external access