---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster Role'

Resources:

  eksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
            AWS:
            - arn:aws:iam::YOUR_CODE_USER_AWS_ACCOUNT:user/YOUR_USER_CREATED
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

Outputs:

  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt eksClusterRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"

# command :
# aws cloudformation create-stack --stack-name eksClusterRole-CloudFormation --region YOUR_AWS_REGION --template-body file://cloudformation-create-role.yml --capabilities "CAPABILITY_IAM"
