version: 2.1

commands:
  destroy-environment:
    description: Delete NEW_BACKEND deployed.
    parameters:
      workflow-id:
        type: string  
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Delete NEW_BACKEND backend
          when: on_fail
          command: |
            NEW_BACKEND=$(curl -H "token: b614fca1-86e7-4215-b1af-6fd45ce24223" --request GET https://api.memstash.io/values/NEW_BACKEND_${CIRCLE_WORKFLOW_ID:0:7})
            kubectl delete deployment,service backend-$NEW_BACKEND

orbs:
  kubernetes: circleci/kubernetes@0.12.0

jobs:

  install-backend-dependencies:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: Back-end install
          command: |
             echo "CIRCLE_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:7}"
             cd backend
             npm i
      - save_cache:
          paths: [backend/node_modules]
          key: backend-install

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: Scan Back-end
          command: |
            cd backend
            npm audit fix --audit-level=critical --force

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: Test Back-end
          command: |
            cd backend
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-install

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    
    steps:
      - checkout
      - kubernetes/install-kubectl

      - run:
          name: Get current backend deployment
          command: |
            aws eks --region us-east-1 update-kubeconfig --name udacity-fred-eks-cluster
            
            OLD_BACKEND=$(kubectl get deployment -o=jsonpath={.items[*].metadata.name})
            echo "OLD_BACKEND=$OLD_BACKEND"
            curl -H "Content-Type: text/plain" -H "token: b614fca1-86e7-4215-b1af-6fd45ce24223" --request PUT --data "$OLD_BACKEND" https://api.memstash.io/values/OLD_BACKEND_${CIRCLE_WORKFLOW_ID:0:7}

            NEW_BACKEND=${CIRCLE_WORKFLOW_ID:0:7}
            echo "NEW_BACKEND=$NEW_BACKEND"
            curl -H "Content-Type: text/plain" -H "token: b614fca1-86e7-4215-b1af-6fd45ce24223" --request PUT --data "$NEW_BACKEND" https://api.memstash.io/values/NEW_BACKEND_${CIRCLE_WORKFLOW_ID:0:7}
            
      - run:
          name: Write deployment.yml
          command: |
            curl https://raw.githubusercontent.com/fr3d3rico/cloud-developer-capstone/main/deployment.yml -o deployment.yml

            SED_REPLACE="s/CIRCLE_WORKFLOW_ID/${CIRCLE_WORKFLOW_ID:0:7}/"

            sed -i $SED_REPLACE deployment.yml

            cat deployment.yml

      - run:
          name: Write service.yml
          command: |
            curl https://raw.githubusercontent.com/fr3d3rico/cloud-developer-capstone/main/service.yml -o service.yml

            SED_REPLACE="s/CIRCLE_WORKFLOW_ID/${CIRCLE_WORKFLOW_ID:0:7}/"

            sed -i $SED_REPLACE service.yml

            cat service.yml

      - run:
          name: Deploy new backend
          command: |
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
      
      - destroy-environment

  wait-some-minutes:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Wait 7 minute
          command: |
            sleep 7m
      - destroy-environment
          
  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apk add --update curl
            pip install awscli
      
      - kubernetes/install-kubectl

      - run:
          name: Backend smoke test.
          command: |
            aws eks --region us-east-1 update-kubeconfig --name udacity-fred-eks-cluster
            
            URL=$(kubectl get service --sort-by=.metadata.creationTimestamp -o=jsonpath={.items[2].status.loadBalancer.ingress[0].hostname} | head -1)
            
            URL="http://${URL}:3000"

            if curl -s ${URL} | grep "Hello World!"
            then
              return 0
            else
              return 1
            fi

      - destroy-environment

  download-update-api-gateway:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apk add --update curl
            pip install awscli
      
      - kubernetes/install-kubectl

      - run:
          name: Download and Update apigateway.yml
          command: |
             aws eks --region us-east-1 update-kubeconfig --name udacity-fred-eks-cluster
             
             URL=$(kubectl get service --sort-by=.metadata.creationTimestamp -o=jsonpath={.items[2].status.loadBalancer.ingress[0].hostname} | head -1)

             curl https://raw.githubusercontent.com/fr3d3rico/cloud-developer-capstone/main/apigateway.yml -o apigateway.yml

             SED_REPLACE="s/NEW_BACKEND/${URL}/"
             sed -i $SED_REPLACE apigateway.yml

             aws apigatewayv2 reimport-api --body file://apigateway.yml --api-id $AWS_API_GATEWAY_ID

      - destroy-environment

  cleanup:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout

        - run:
            name: Install dependencies
            command: |
              apk add --update curl
              pip install awscli
        
        - kubernetes/install-kubectl

        - run:
            name: Delete OLD_BACKEND backend
            command: |
              aws eks --region us-east-1 update-kubeconfig --name udacity-fred-eks-cluster

              OLD_BACKEND=$(curl -H "token: b614fca1-86e7-4215-b1af-6fd45ce24223" --request GET https://api.memstash.io/values/OLD_BACKEND_${CIRCLE_WORKFLOW_ID:0:7})
              
              kubectl delete deployment,service $OLD_BACKEND

        - destroy-environment

workflows:
  default:
    jobs:
      - install-backend-dependencies
      - scan-backend:
          requires: [install-backend-dependencies]
      - test-backend:
          requires: [scan-backend]
      - deploy-infrastructure:
          requires: [test-backend]
          filters:
            branches:
              only: [main]
      - wait-some-minutes:
          requires: [deploy-infrastructure]
      - smoke-test:
          requires: [wait-some-minutes]
      - download-update-api-gateway:
          requires: [smoke-test]
      - cleanup:
          requires: [download-update-api-gateway]